# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.2.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGroupBox, QLabel,
    QListView, QMainWindow, QPushButton, QSizePolicy,
    QTabWidget, QTextBrowser, QTextEdit, QWidget)

class Ui_PhasmoCompanion(object):
    def setupUi(self, PhasmoCompanion):
        if not PhasmoCompanion.objectName():
            PhasmoCompanion.setObjectName(u"PhasmoCompanion")
        PhasmoCompanion.resize(791, 552)
        self.centralwidget = QWidget(PhasmoCompanion)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(430, 10, 361, 241))
        self.evidenceLabel1 = QLabel(self.groupBox)
        self.evidenceLabel1.setObjectName(u"evidenceLabel1")
        self.evidenceLabel1.setGeometry(QRect(80, 40, 201, 41))
        font = QFont()
        font.setPointSize(18)
        self.evidenceLabel1.setFont(font)
        self.evidenceLabel1.setAlignment(Qt.AlignCenter)
        self.cycleEvidenceButtonL1 = QPushButton(self.groupBox)
        self.cycleEvidenceButtonL1.setObjectName(u"cycleEvidenceButtonL1")
        self.cycleEvidenceButtonL1.setGeometry(QRect(20, 50, 31, 24))
        self.cycleEvidenceButtonR1 = QPushButton(self.groupBox)
        self.cycleEvidenceButtonR1.setObjectName(u"cycleEvidenceButtonR1")
        self.cycleEvidenceButtonR1.setGeometry(QRect(310, 50, 31, 24))
        self.line = QFrame(self.groupBox)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(20, 80, 321, 16))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.cycleEvidenceButtonR2 = QPushButton(self.groupBox)
        self.cycleEvidenceButtonR2.setObjectName(u"cycleEvidenceButtonR2")
        self.cycleEvidenceButtonR2.setGeometry(QRect(310, 100, 31, 24))
        self.cycleEvidenceButtonL2 = QPushButton(self.groupBox)
        self.cycleEvidenceButtonL2.setObjectName(u"cycleEvidenceButtonL2")
        self.cycleEvidenceButtonL2.setGeometry(QRect(20, 100, 31, 24))
        self.line_2 = QFrame(self.groupBox)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(20, 130, 321, 16))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.evidenceLabel2 = QLabel(self.groupBox)
        self.evidenceLabel2.setObjectName(u"evidenceLabel2")
        self.evidenceLabel2.setGeometry(QRect(80, 90, 201, 41))
        self.evidenceLabel2.setFont(font)
        self.evidenceLabel2.setAlignment(Qt.AlignCenter)
        self.cycleEvidenceButtonR3 = QPushButton(self.groupBox)
        self.cycleEvidenceButtonR3.setObjectName(u"cycleEvidenceButtonR3")
        self.cycleEvidenceButtonR3.setGeometry(QRect(310, 150, 31, 24))
        self.cycleEvidenceButtonL3 = QPushButton(self.groupBox)
        self.cycleEvidenceButtonL3.setObjectName(u"cycleEvidenceButtonL3")
        self.cycleEvidenceButtonL3.setGeometry(QRect(20, 150, 31, 24))
        self.line_3 = QFrame(self.groupBox)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(20, 180, 321, 16))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.evidenceLabel3 = QLabel(self.groupBox)
        self.evidenceLabel3.setObjectName(u"evidenceLabel3")
        self.evidenceLabel3.setGeometry(QRect(80, 140, 201, 41))
        self.evidenceLabel3.setFont(font)
        self.evidenceLabel3.setAlignment(Qt.AlignCenter)
        self.resetEvidenceButton = QPushButton(self.groupBox)
        self.resetEvidenceButton.setObjectName(u"resetEvidenceButton")
        self.resetEvidenceButton.setGeometry(QRect(260, 200, 80, 24))
        self.line_4 = QFrame(self.groupBox)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(20, 30, 321, 16))
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(430, 260, 361, 291))
        self.ghostsListView = QListView(self.groupBox_2)
        self.ghostsListView.setObjectName(u"ghostsListView")
        self.ghostsListView.setGeometry(QRect(10, 30, 341, 251))
        font1 = QFont()
        font1.setPointSize(12)
        font1.setBold(True)
        self.ghostsListView.setFont(font1)
        self.infoTabWidget = QTabWidget(self.centralwidget)
        self.infoTabWidget.setObjectName(u"infoTabWidget")
        self.infoTabWidget.setGeometry(QRect(10, 10, 411, 541))
        self.ghostInfoTab = QWidget()
        self.ghostInfoTab.setObjectName(u"ghostInfoTab")
        self.notesBrowser = QTextBrowser(self.ghostInfoTab)
        self.notesBrowser.setObjectName(u"notesBrowser")
        self.notesBrowser.setGeometry(QRect(10, 10, 381, 491))
        self.infoTabWidget.addTab(self.ghostInfoTab, "")
        self.mapInfoTab = QWidget()
        self.mapInfoTab.setObjectName(u"mapInfoTab")
        self.mapBrowser = QTextBrowser(self.mapInfoTab)
        self.mapBrowser.setObjectName(u"mapBrowser")
        self.mapBrowser.setGeometry(QRect(10, 10, 381, 461))
        self.cycleMapButtonR = QPushButton(self.mapInfoTab)
        self.cycleMapButtonR.setObjectName(u"cycleMapButtonR")
        self.cycleMapButtonR.setGeometry(QRect(350, 480, 31, 24))
        self.mapLabel = QLabel(self.mapInfoTab)
        self.mapLabel.setObjectName(u"mapLabel")
        self.mapLabel.setGeometry(QRect(60, 470, 281, 41))
        font2 = QFont()
        font2.setPointSize(14)
        self.mapLabel.setFont(font2)
        self.mapLabel.setAlignment(Qt.AlignCenter)
        self.cycleMapButtonL = QPushButton(self.mapInfoTab)
        self.cycleMapButtonL.setObjectName(u"cycleMapButtonL")
        self.cycleMapButtonL.setGeometry(QRect(20, 480, 31, 24))
        self.infoTabWidget.addTab(self.mapInfoTab, "")
        self.settingsTab = QWidget()
        self.settingsTab.setObjectName(u"settingsTab")
        self.groupBox_4 = QGroupBox(self.settingsTab)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 225, 381, 281))
        self.log_edit = QTextEdit(self.groupBox_4)
        self.log_edit.setObjectName(u"log_edit")
        self.log_edit.setGeometry(QRect(10, 20, 361, 251))
        font3 = QFont()
        self.log_edit.setFont(font3)
        self.groupBox_3 = QGroupBox(self.settingsTab)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 10, 381, 208))
        self.infoTabWidget.addTab(self.settingsTab, "")
        PhasmoCompanion.setCentralWidget(self.centralwidget)

        self.retranslateUi(PhasmoCompanion)

        self.infoTabWidget.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(PhasmoCompanion)
    # setupUi

    def retranslateUi(self, PhasmoCompanion):
        PhasmoCompanion.setWindowTitle(QCoreApplication.translate("PhasmoCompanion", u"PhasmoCompanion", None))
        self.groupBox.setTitle(QCoreApplication.translate("PhasmoCompanion", u"Selected Evidence", None))
        self.evidenceLabel1.setText(QCoreApplication.translate("PhasmoCompanion", u"DOTS Projector", None))
        self.cycleEvidenceButtonL1.setText(QCoreApplication.translate("PhasmoCompanion", u"<", None))
        self.cycleEvidenceButtonR1.setText(QCoreApplication.translate("PhasmoCompanion", u">", None))
        self.cycleEvidenceButtonR2.setText(QCoreApplication.translate("PhasmoCompanion", u">", None))
        self.cycleEvidenceButtonL2.setText(QCoreApplication.translate("PhasmoCompanion", u"<", None))
        self.evidenceLabel2.setText(QCoreApplication.translate("PhasmoCompanion", u"DOTS Projector", None))
        self.cycleEvidenceButtonR3.setText(QCoreApplication.translate("PhasmoCompanion", u">", None))
        self.cycleEvidenceButtonL3.setText(QCoreApplication.translate("PhasmoCompanion", u"<", None))
        self.evidenceLabel3.setText(QCoreApplication.translate("PhasmoCompanion", u"DOTS Projector", None))
        self.resetEvidenceButton.setText(QCoreApplication.translate("PhasmoCompanion", u"Reset", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("PhasmoCompanion", u"Possible Ghosts", None))
        self.infoTabWidget.setTabText(self.infoTabWidget.indexOf(self.ghostInfoTab), QCoreApplication.translate("PhasmoCompanion", u"Ghost Info", None))
        self.cycleMapButtonR.setText(QCoreApplication.translate("PhasmoCompanion", u">", None))
        self.mapLabel.setText(QCoreApplication.translate("PhasmoCompanion", u"DOTS Projector", None))
        self.cycleMapButtonL.setText(QCoreApplication.translate("PhasmoCompanion", u"<", None))
        self.infoTabWidget.setTabText(self.infoTabWidget.indexOf(self.mapInfoTab), QCoreApplication.translate("PhasmoCompanion", u"Map Info", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("PhasmoCompanion", u"Log", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("PhasmoCompanion", u"HotKey Editor", None))
        self.infoTabWidget.setTabText(self.infoTabWidget.indexOf(self.settingsTab), QCoreApplication.translate("PhasmoCompanion", u"Settings", None))
    # retranslateUi



